//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SerialPortMon.rc
//
#define IDD_SERIALPORTMON_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SHORTKEY             129
#define IDD_DIALOG_CONNECTION           130
#define IDD_DIALOG1                     131
#define IDD_DIALOG_CONFIGURATION        131
#define IDD_DIALOG_SERIAL               132
#define IDD_DIALOG_MODEM                133
#define IDR_WAVE_LOGOFF                 134
#define IDD_DIALOG_ETHERNET             134
#define IDR_WAVE_LOGON                  135
#define IDD_DIALOG_UDP                  135
#define IDB_LAMP_DISABLE                136
#define IDB_LAMP_OFF                    137
#define IDB_LAMP_ON                     138
#define IDC_BUTTON_SHORTKEY             1000
#define IDC_EDIT_MESSAGE_LOG            1001
#define IDC_RADIO_TCPS                  1001
#define IDC_EDIT_INPUT                  1002
#define IDC_RADIO_TCPC                  1002
#define IDC_BUTTON_SEND                 1003
#define IDC_EDIT_DELAY1                 1003
#define IDC_IPADDRESS_DEST              1003
#define IDC_RADIO_TCPC2                 1003
#define IDC_RADIO_COM                   1003
#define IDC_EDIT_REPEAT1                1004
#define IDC_RADIO_INPUT_HEX             1004
#define IDC_EDIT_DELAY2                 1005
#define IDC_RADIO_INPUT_ASCII           1005
#define IDC_CHECK_RTS                   1006
#define IDC_EDIT_REPEAT2                1006
#define IDC_BUTTON_CONNECT_CLOSE        1007
#define IDC_EDIT_DELAY3                 1007
#define IDC_CHECK_DTR                   1008
#define IDC_EDIT_REPEAT3                1008
#define IDC_CHECK_CTS                   1009
#define IDC_EDIT_DELAY4                 1009
#define IDC_CHECK_DSR                   1010
#define IDC_EDIT_REPEAT4                1010
#define IDC_CHECK_RI                    1011
#define IDC_EDIT_DELAY5                 1011
#define IDC_CHECK_LINEFEED_CR_LF        1011
#define IDC_CHECK_REPLACE_CRLF          1011
#define IDC_CHECK_CD                    1012
#define IDC_EDIT_REPEAT5                1012
#define IDC_RADIO_UDP                   1012
#define IDC_EDIT_DELAY6                 1013
#define IDC_RADIO_SUFFIX_CR             1013
#define IDC_EDIT_DEST_PORT              1013
#define IDC_EDIT_REPEAT6                1014
#define IDC_RADIO_SUFFIX_LF             1014
#define IDC_EDIT_DELAY7                 1015
#define IDC_RADIO_SUFFIX_CRLF           1015
#define IDC_EDIT_PREFIX                 1016
#define IDC_EDIT_REPEAT7                1016
#define IDC_EDIT_DELAY8                 1017
#define IDC_RADIO_SUFFIX_EDIT           1017
#define IDC_EDIT_SUFFIX                 1018
#define IDC_EDIT_REPEAT8                1018
#define IDC_SPIN_SEND                   1019
#define IDC_BUTTON_CONFIGURATION        1021
#define IDC_CHECK_ASCII_HEX1            1021
#define IDC_BUTTON_CLEAR                1022
#define IDC_BUTTON_SEND1                1022
#define IDC_STATIC_IP                   1022
#define IDC_BUTTON_SAVE                 1023
#define IDC_COMBO_SHORTKEY1             1023
#define IDC_CHECK_CTRL1                 1024
#define IDC_COMBO_DATABITS              1024
#define IDC_RADIO_MESSAGE_HEX           1024
#define IDC_CHECK_ALT1                  1025
#define IDC_COMBO_PARITY                1025
#define IDC_RADIO_RECORD_ASCII          1025
#define IDC_CHECK_SHIFT1                1026
#define IDC_COMBO_STOPBITS              1026
#define IDC_EDIT_MESSAGE1               1027
#define IDC_COMBO_FLOWCTL               1027
#define IDC_EDIT_MESSAGE2               1028
#define IDC_COMBO_PORT                  1028
#define IDC_CHECK_ASCII_HEX2            1029
#define IDC_EDIT_BUFFER_LINES           1029
#define IDC_BUTTON_SEND2                1030
#define IDC_COMBO_SHORTKEY2             1031
#define IDC_SPIN_BUFFER_LINES           1031
#define IDC_CHECK_CTRL2                 1032
#define IDC_CHECK_PLAY_SOUND            1032
#define IDC_CHECK_ALT2                  1033
#define IDC_CHECK_CONNECT_AT_STARTUP    1033
#define IDC_CHECK_SHIFT2                1034
#define IDC_CHECK_ECHO_TYPED_CHARS      1034
#define IDC_EDIT_MESSAGE3               1035
#define IDC_CHECK_7BITS_ASCII           1035
#define IDC_CHECK_ASCII_HEX3            1036
#define IDC_CHECK_LINEND_CRLF           1036
#define IDC_BUTTON_SEND3                1037
#define IDC_COMBO_SHORTKEY3             1038
#define IDC_CHECK_CTRL3                 1039
#define IDC_CHECK_ALT3                  1040
#define IDC_CHECK_SHIFT3                1041
#define IDC_EDIT_MESSAGE4               1042
#define IDC_CHECK_ASCII_HEX4            1043
#define IDC_BUTTON_SEND4                1044
#define IDC_COMBO_SHORTKEY4             1045
#define IDC_CHECK_CTRL4                 1046
#define IDC_CHECK_ALT4                  1047
#define IDC_CHECK_SHIFT4                1048
#define IDC_EDIT_MESSAGE5               1049
#define IDC_CHECK_ASCII_HEX5            1050
#define IDC_BUTTON_SEND5                1051
#define IDC_COMBO_SHORTKEY5             1052
#define IDC_CHECK_CTRL5                 1053
#define IDC_CHECK_ALT5                  1054
#define IDC_CHECK_SHIFT5                1055
#define IDC_EDIT_MESSAGE6               1056
#define IDC_CHECK_ASCII_HEX6            1057
#define IDC_BUTTON_SEND6                1058
#define IDC_COMBO_SHORTKEY6             1059
#define IDC_CHECK_CTRL6                 1060
#define IDC_CHECK_ALT6                  1061
#define IDC_CHECK_SHIFT6                1062
#define IDC_EDIT_MESSAGE7               1063
#define IDC_CHECK_ASCII_HEX7            1064
#define IDC_BUTTON_SEND7                1065
#define IDC_COMBO_SHORTKEY7             1066
#define IDC_CHECK_CTRL7                 1067
#define IDC_CHECK_ALT7                  1068
#define IDC_CHECK_SHIFT7                1069
#define IDC_EDIT_MESSAGE8               1070
#define IDC_CHECK_ASCII_HEX8            1071
#define IDC_BUTTON_SEND8                1072
#define IDC_COMBO_SHORTKEY8             1073
#define IDC_CHECK_CTRL8                 1074
#define IDC_CHECK_ALT8                  1075
#define IDC_CHECK_SHIFT8                1076
#define IDC_CHECK_HIDE_SHORTKEY         1077
#define IDC_COMBO_BPS                   1078
#define IDC_COMBO_SHORTKEY9             1078
#define IDC_CHECK_CTRL9                 1079
#define IDC_BUTTON1                     1080
#define IDC_BUTTON_STOP                 1080
#define IDC_CHECK_BREAK                 1081
#define IDC_CHECK_ALT9                  1081
#define IDC_BUTTON_XON                  1082
#define IDC_CHECK_SHIFT9                1082
#define IDC_BUTTON_XOFF                 1083
#define IDC_STATIC_CTS                  1084
#define IDC_STATIC_DSR                  1085
#define IDC_STATIC_RUN1                 1085
#define IDC_STATIC_RING                 1086
#define IDC_STATIC_RUN2                 1086
#define IDC_STATIC_HOMEPAGE             1086
#define IDC_STATIC_RLSD                 1087
#define IDC_STATIC_RUN3                 1087
#define IDC_CHECK1                      1087
#define IDC_CHECK_MESSAGE_DISPLAY       1087
#define IDC_CHECK_BROADCAST             1087
#define IDC_CHECK_DISPLAY_SEND          1087
#define IDC_CHECK_SENDRECV_MARK         1087
#define IDC_STATIC_RUN4                 1088
#define IDC_CHECK_MESSAGE_DISPLAY2      1088
#define IDC_CHECK_DISPLAY_RECV          1088
#define IDC_STATIC_RUN5                 1089
#define IDC_STATIC_RUN6                 1090
#define IDC_STATIC_RUN7                 1091
#define IDC_STATIC_RUN8                 1092
#define IDC_EDIT1                       1093
#define IDC_EDIT_KEY_PRESSED            1093
#define IDC_EDIT_IP                     1093
#define IDC_COMBO_LOCAL_IP              1094
#define IDC_EDIT2                       1095
#define IDC_EDIT_PORT                   1095
#define IDC_COMBO_REPLACE_CHAR          1096
#define IDC_STATIC_VERSION              1097
#define IDC_COMBO_TIME_DISPLAY          1097
#define IDC_CHECK_AUTO_                 1098
#define IDC_CHECK_AUTO_WORD_WRAP        1098
#define IDC_STATIC1                     1099
#define IDC_STATIC2                     1100
#define IDC_STATIC3                     1101
#define IDC_STATIC4                     1102
#define IDC_STATIC5                     1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
